# Generated by Django 3.2.3 on 2021-05-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(max_length=10)),
                ('alpha', models.FloatField(default=0)),
                ('beta', models.FloatField(default=0)),
                ('turn', models.FloatField(default=0)),
                ('unknown', models.FloatField(default=1)),
                ('length', models.IntegerField()),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
    ]
