# Generated by Django 3.2.3 on 2021-05-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteindb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='dataType',
            field=models.CharField(default='', max_length=3),
        ),
    ]
