# Generated by Django 3.2.3 on 2021-05-27 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proteindb', '0002_protein_datatype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protein',
            name='slug',
        ),
    ]
