# Generated by Django 3.2.3 on 2021-06-03 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proteindb', '0004_auto_20210603_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simprotein',
            name='unknown',
        ),
    ]
