# Generated by Django 3.2.3 on 2021-06-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteindb', '0005_remove_simprotein_unknown'),
    ]

    operations = [
        migrations.CreateModel(
            name='protein',
            fields=[
                ('accession', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='uniprotein',
            name='id',
        ),
        migrations.AddField(
            model_name='simprotein',
            name='simType',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='uniprotein',
            name='known',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='uniprotein',
            name='accession',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
