# Generated by Django 3.2.3 on 2021-06-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteindb', '0006_auto_20210607_1134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='protein',
        ),
        migrations.AlterField(
            model_name='simprotein',
            name='accession',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='simprotein',
            name='simType',
            field=models.CharField(default='', max_length=4),
        ),
    ]
