# Generated by Django 3.2.3 on 2021-06-08 16:13

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('proteindb', '0007_auto_20210608_1102'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='simprotein',
            managers=[
                ('simManage', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='uniprotein',
            managers=[
                ('uniManage', django.db.models.manager.Manager()),
            ],
        ),
    ]
