# Generated by Django 3.2.3 on 2021-06-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteindb', '0008_auto_20210608_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='accessionLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.TextField(null=True)),
            ],
        ),
    ]
