# Generated by Django 3.2.3 on 2021-06-14 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proteindb', '0009_accessionlookup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='accessionLookup',
            new_name='csvAccessionList',
        ),
    ]
