# Generated by Django 3.2.3 on 2021-06-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteindb', '0010_rename_accessionlookup_csvaccessionlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='csvList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='csvAccessionList',
        ),
    ]
