# Generated by Django 3.2.3 on 2021-06-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proteindb', '0011_auto_20210614_1035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='csvList',
        ),
    ]
