# Generated by Django 3.2.3 on 2021-06-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteindb', '0012_delete_csvlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='csvAccession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(max_length=20)),
            ],
        ),
    ]
