# Generated by Django 3.2.3 on 2021-06-18 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proteindb', '0013_csvaccession'),
    ]

    operations = [
        migrations.CreateModel(
            name='masterProtein',
            fields=[
                ('accession', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='simprotein',
            name='id',
        ),
        migrations.AlterField(
            model_name='simprotein',
            name='accession',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='simprotein',
            name='master',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='proteindb.masterprotein'),
        ),
        migrations.AddField(
            model_name='uniprotein',
            name='master',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='proteindb.masterprotein'),
        ),
    ]
