# Generated by Django 3.2.3 on 2021-06-18 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proteindb', '0014_auto_20210618_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniprotein',
            name='master',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='proteindb.masterprotein', unique=True),
        ),
    ]
