# Generated by Django 3.2.3 on 2021-06-18 15:54

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('proteindb', '0015_alter_uniprotein_master'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='masterprotein',
            managers=[
                ('masterManage', django.db.models.manager.Manager()),
            ],
        ),
    ]
