# Generated by Django 3.2.3 on 2021-06-18 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proteindb', '0016_alter_masterprotein_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simprotein',
            name='master',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sim', to='proteindb.masterprotein'),
        ),
        migrations.AlterField(
            model_name='uniprotein',
            name='master',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='uni', to='proteindb.masterprotein', unique=True),
        ),
    ]
